-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.candidates
(
    id integer NOT NULL,
    "firstName" character varying(30) NOT NULL,
    "lastName" character varying(30) NOT NULL,
    "identityNumber" character varying(11) NOT NULL,
    "birthOfYear" date NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public."candidatesVerify"
(
    id integer NOT NULL,
    "candidatesId" integer NOT NULL,
    "isVerify" boolean NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.employer
(
    id integer NOT NULL,
    "companyName" character varying(50) NOT NULL,
    "companyWebsite" character varying(50) NOT NULL,
    "phoneNumber" character varying(12) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public."employerApprovalByEmployees"
(
    id integer NOT NULL,
    "staffId" integer NOT NULL,
    "employerId" integer NOT NULL,
    "isVerify" boolean NOT NULL,
    "confirmedDate" date NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public."employerVerify"
(
    id integer NOT NULL,
    "employerId" integer NOT NULL,
    "isVerify" boolean NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.job_positions
(
    id integer NOT NULL,
    "position" character varying(50) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public."systemStaff"
(
    id integer NOT NULL,
    "firstName" character varying(30) NOT NULL,
    "lastName" character varying(30) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.users
(
    id integer NOT NULL,
    mail character varying(50) NOT NULL,
    password character varying(50) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.verify_code
(
    id integer NOT NULL,
    "verifyCode" character varying(10) NOT NULL,
    "isVerify" boolean NOT NULL,
    "confirmedDate" date NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE public.candidates
    ADD FOREIGN KEY (id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public."candidatesVerify"
    ADD FOREIGN KEY ("candidatesId")
    REFERENCES public.candidates (id)
    NOT VALID;


ALTER TABLE public."candidatesVerify"
    ADD FOREIGN KEY (id)
    REFERENCES public.verify_code (id)
    NOT VALID;


ALTER TABLE public.employer
    ADD FOREIGN KEY (id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public."employerApprovalByEmployees"
    ADD FOREIGN KEY (id)
    REFERENCES public.verify_code (id)
    NOT VALID;


ALTER TABLE public."employerApprovalByEmployees"
    ADD FOREIGN KEY ("staffId")
    REFERENCES public."systemStaff" (id)
    NOT VALID;


ALTER TABLE public."employerApprovalByEmployees"
    ADD FOREIGN KEY ("employerId")
    REFERENCES public.employer (id)
    NOT VALID;


ALTER TABLE public."employerVerify"
    ADD FOREIGN KEY ("employerId")
    REFERENCES public.employer (id)
    NOT VALID;


ALTER TABLE public."employerVerify"
    ADD FOREIGN KEY (id)
    REFERENCES public.verify_code (id)
    NOT VALID;


ALTER TABLE public."systemStaff"
    ADD FOREIGN KEY (id)
    REFERENCES public.users (id)
    NOT VALID;

END;
